### ISSUE TITLE
[Question] E-stop/Cyc start/Feed hold buttons type

### ISSUE THREAD

**Issue by Shkolik** [phil-barrett/grblHAL-teensy-4.x#20]
Hello!

I'm trying to wire your breakout board and could not figure out what buttons type to buy. 

I assume they should be NC momentary? Am I right? Or they should be latching - same as safety door switch?

Also, If you can point me were and how connect encoders for feed/speed override It would be great!

Thank you for your work - amazing board!

**Comment by phil-barrett** [comment]
Yes. NC momentary switches. 

I don't have the pinout handy but you can find it in the source code - in the t41u5xbb_map.h file. I will be back on the 6th (covid tests willing) and can help you then if you are still stuck.
