### ISSUE TITLE
URL for your blog?

### ISSUE THREAD

**Issue by frdfsnlght** [phil-barrett/grblHAL-teensy-4.x#5]
I came across your blog once and I thought I bookmarked it, but apparently I didn't and now I can't find my way back. I remember it has some interesting content that I want to look at again. Where can I find it? Is there a way for you to include the URL in some of your (applicable) repos?

**Comment by phil-barrett** [comment]
easy to remember - grbl.org.

actual [link to blog](https://www.grbl.org/blog).

**Comment by frdfsnlght** [comment]
That's certainly easy to remember! Thanks much.
