### ISSUE TITLE
Board dimensions?

### ISSUE THREAD

**Issue by bertvdijk** [phil-barrett/grblHAL-teensy-4.x#76]
Hi, I couldn’t find the dimensions of the board in the repo. Specifically I’m interested in the mounting hole size and distances between the holes. 

Thank you!

**Comment by phil-barrett** [comment]
It's in the [manual](https://github.com/phil-barrett/grblHAL-teensy-4.x/blob/master/T41U5XBB%20v207.pdf) towards the end.
